### PR TITLE
enhancements

### PR DESCRIPTION
**Pull request by naderio**
initial work done by @rajivnarayana (refactoring and iOS implementation).
implemented the same in android and added support for other marker properties 

* add `markerSelect` event to MapView
* add `cameraChanged` event to MapView
* add `Camera`
* add `Position`
* add `Marker` 
* ...

basically we're able to do the following:

# Map
```
<maps:mapView latitude="{{ latitude }}" longitude="{{ longitude }}"
  mapReady="onMapReady" 
  markerSelect="onMarkerSelect" 
  cameraChanged="onCameraChanged" />
```

# Marker and Position
```
var marker = new maps.Marker();
marker.alpha = 0.8; // not yet on iOS
marker.flat = true; // not yet on iOS
marker.draggable = true; // not yet on iOS
marker.visible = true; // not yet on iOS
var icon = new Image();
icon.imageSource = imageSource.fromResource('ic_navigation_black_24dp');
marker.icon = icon;
marker.position = maps.Position.positionFromLatLng(location.latitude, location.longitude);
marker.rotation = rotation; // not yet on iOS
mapView.addMarker(marker);
```

### CODE REVIEW

**Comment by rajivnarayana** [comment]
@naderio, you beat me to adding events and properties for android, lol. Thanks.

**Comment by dapriett** [comment]
Hey @naderio @rajivnarayana - looks good so far.  Been looking to add better Markers support.  Nice work with the Typescript rewrite too - was considering doing that at some point.

Do the `markerSelect` and `cameraChanged` events actually work yet?  I tried the demo, doesn't seem like they are being triggered.  I browsed the code, didn't see where the listeners are being attached to the Google SDK mapview.

**Comment by naderio** [comment]
@dapriett my bad, now the events are implemented
I'm also looking into map initial options and map configuration, but lets keep that to another PR
Thanks!

**Comment by rajivnarayana** [comment]
Looks good. Except that .js files are no longer needed in git and .ts files can be ignored in .npmignore. Not a big deal though.

**Comment by dapriett** [comment]
Hi @naderio - nice work, just saw a couple issues:

I ran the demo and it appears the `cameraChanged` event is stuck in an infinite loop (tested on Android)
```
JS: onMapReady
JS: Setting a marker...
JS: Camera changed: {"latitude":-33.85771909507438,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.85543823796389,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.853157041504794,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.85087606256382,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.84859502271432,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.846313921958284,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.84403276029768,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.84175181620779,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.83947081123218,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.83718974537285,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.83490861863179,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.832627431011,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.83034534698117,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.82806348054885,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.82578127468773,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.82349928644299,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.82121723729875,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.81893512725699,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.81665323487475,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.81437100305141,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.81208898890643,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.809806913886796,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
JS: Camera changed: {"latitude":-33.807524777994495,"longitude":151.19999695569277,"zoom":8,"bearing":0,"tilt":0}
```

It looks like when we set the `cameraPosition` it triggers the `cameraChanged`, but with a slightly different latitude then what we set ([possible bug](https://code.google.com/p/gmaps-api-issues/issues/detail?id=5353) in the sdk?).  This causes us to set the latitude property, triggering the `updateCamera` function to be called, starting the cycle again.

Maybe we can add a `_processingCameraEvent` property to the MapView.

Then in the `onMapPropertyChanged` do this
```
function onMapPropertyChanged(data: PropertyChangeData) {
    let mapView = <MapView>data.object;
    if(!mapView._processingCameraEvent) mapView.updateCamera();
}
```

Then change the cameraEvent listeners 
```
gMap.setOnCameraChangeListener(new com.google.android.gms.maps.GoogleMap.OnCameraChangeListener({
            onCameraChange: function(cameraPosition) {
              mapView._processingCameraEvent = true
              ...
              mView.notifyCameraEvent(MapViewCommon.cameraChangedEvent, {
                latitude: cameraPosition.target.latitude,
                longitude: cameraPosition.target.longitude,
                zoom: cameraPosition.zoom,
                bearing: cameraPosition.bearing,
                tilt: cameraPosition.tilt
              });
              mapView._processingCameraEvent = false
            }
}));
```

I also tried running the demo with iOS - I received the following when it tried to add the marker with the icon - any ideas?
```
[UIImageView images]: unrecognized selector sent to instance 0x7b0c6380
```

Once those things are fixed, we should be good to merge and upload a new version.

**Comment by dapriett** [comment]
For the iOS icon marker, you'll just need to set the icon as a `UIImage`, not a `UIImageView` - which you can get from the UIImageView:

```
export class Marker extends MarkerBase {
   ...
    set icon(icon : Image) {
        this._icon = icon;
        this._ios.icon = icon.ios.image;
    }
...
}

```

**Comment by naderio** [comment]
should be ok now

**Comment by dapriett** [comment]
Nice work!  Merged it in, removed the JS files from git, and pushed it up to NPM.

**Comment by naderio** [comment]
Thanks!

**Pull request merged**
