### PR TITLE
implement polyline

### PR DESCRIPTION
**Pull request by naderio**
implement and test for android
ios not implemented

### CODE REVIEW

**Comment by naderio** [comment]
android implementation works fine. (zIndex untested, tap event not implemented)
ios untested, most probably wont work. (help with this, anyone?)
@dapriett what do you think?

**Comment by naderio** [comment]
implemented ios, remains untested

**Comment by dapriett** [comment]
thanks @naderio - there was a couple iOS issues with Polyline and Marker icon image from string which are resolved https://github.com/dapriett/nativescript-google-maps-sdk/commit/ec3482d7b4bc99824171c21797fa069f7264ee35

**Comment by naderio** [comment]
thanks!

**Pull request merged**
